include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  linkly-clicks-dlq {}

  linkly-clicks {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "linkly-clicks-dlq"
      maxReceiveCount = 5
    }
  }
}
