apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkly-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ErnestoJim/linkly.git
    targetRevision: main
    path: deploy/helm/linkly
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: linkly-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
