apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkly.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "linkly.fullname" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "linkly.fullname" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          resources: {{ toYaml .Values.api.resources | nindent 12 }}
